### ISSUE TITLE
Add tmp.hostname file?

### ISSUE THREAD

**Issue by jtchilders** [PanDAWMS/panda-harvester#24]
Hi Tadashi,

On HPCs, when you login you end up on any number of login nodes. Sometimes I start Harvester and then exit the machine. Then I forget on which of the 10 login nodes I started Harvester and have to login to each to find out where :)  Can you make a 'tmp.hostname' file similar to the 'tmp.pid' file which holds the hostname on which Harvester was launched?

Thanks,
Taylor

**Comment by tmaeno** [comment]
I've added --hostname_file to master.py in the git repo.
```sh
$ python .../master.py --pid .../tmp.pid --hostname_file .../tmp.hostname
```
