### ISSUE TITLE
Config/Template Repo

### ISSUE THREAD

**Issue by jtchilders** [PanDAWMS/panda-harvester#27]
The repo currently has top level 'examples' and 'templates' folders. Could we add a 'site_files' folder under which each site could have a folder where they could store the latest version of their submit templates and local 'cfg' files and queue config json files, etc? As people get their Harvester instances up and running, others can look at site config files for help.

What do you think?

**Comment by tmaeno** [comment]
Fernando created before a git-repository for that purpose

https://github.com/PanDAWMS/harvester_configurations

I think everyone in panda dev team can push changes.

**Comment by fbarreir** [comment]
Yes, everyone in panda dev can push into the harvester_configurations repository. Please feel free to add the site_files folder there, unless you have some strong opinion against a separate repo.

**Comment by jtchilders** [comment]
No That's perfect thanks!


J. Taylor Childers
Argonne National Laboratory
High Energy Physics Division
Building 360, Room C-217
Office: +1 (630) 252-4212
Mobile: +1 (331) 302-4647

**Comment by dougbenjamin** [comment]
Hi,

   Shouldn't  each sites version of  panda_harvester.cfg  be stored there also.

Doug
