### ISSUE TITLE
Job submission fails with local Condor

### ISSUE THREAD

**Issue by virthead** [PanDAWMS/panda-harvester#289]
https://github.com/PanDAWMS/panda-harvester/blob/5bd906cc1510f048fa55a64cdab6889323ac8ee4/pandaharvester/harvestersubmitter/htcondor_submitter.py#L713

Hello guys,

I use a local Condor installation, no pool. In order to force Harvester to work with the local, I've changed Submitter section in common_grid_queueconfig_template.json: condorSchedd and condorPool were removed. Otherwise, Harvester tried to find Condor pool. But with the local Condor there is no Condor SchedName in the config, and log_base_url = re.sub(r'\[ScheddHostname\]', schedd_hostname, self.logBaseURL) fails.

Cheers

**Comment by mightqxc** [comment]
Hi Artem,
If one has local Condor installation, in common_grid_queueconfig_template.json one does not need the placeholder "[ScheddHostname]" in logBaseURL (which is for multiple schedds); put a direct hostname instead. For example: "logBaseURL": "http://my.hostname.cern.ch/condor_log"

**Comment by virthead** [comment]
Hello FaHui,

Ok, doing right now, thanks for the hint. Can see jobs in the Condor, cool)

Cheers
